version: '3.7'

services:
  myindo-web-prod:
    build:
      context: .
      dockerfile: Dockerfile-myindo-web
    environment:
      DOCKER_REGISTRY: ${DOCKER_REGISTRY:-docker-hub.solusi-k8s.com}
      DOCKER_USER: ${DOCKER_USER:-myindo}
      DOCKER_IMAGE: ${DOCKER_IMAGE:-myindo-myindo-web}
      DOCKER_VERSION: ${DOCKER_VERSION:-v1.0.1-dev}
    image: '${DOCKER_REGISTRY:-docker-hub.solusi-k8s.com}/${DOCKER_USER:-myindo}/${DOCKER_IMAGE:-myindo-web}:${DOCKER_VERSION:-v1.0.1-dev}'
