FROM node:jod-alpine as builder

# Set the working directory
WORKDIR /app

COPY . .
RUN npm install --verbose

# Add the source code to app
# COPY ./ /usr/local/app/

# COPY .env-platform-ulp-develop .env

RUN npm run build

RUN ls -al

FROM node:jod

LABEL Component="myindo-web" \
  Name="myindo/myindo-web" \
  Version="v1.0.1" \
  Release="1" \
  org.opencontainers.image.authors="sahir@myindo.id"

WORKDIR /app

COPY --from=builder /app/build build/
COPY --from=builder /app/src/index.js build/
# COPY --from=builder /app/.env-wararena-dahboard-develop /build/.env 

COPY --from=builder /app/node_modules node_modules/

COPY package.json .

EXPOSE 3000

CMD ["node","build/index.js"]
