<script lang="ts">
</script>

<svelte:head>
	<title>Disclaimer — MyIndo Cyber Media</title>
</svelte:head>

<main class="min-h-screen bg-gray-950 px-6 pb-20 pt-28 text-white md:px-16 lg:px-24 xl:px-32">
	<div class="mx-auto max-w-4xl">
		<h1 class="mb-2 text-4xl font-bold">Disclaimer</h1>
		<p class="mb-10 text-sm text-gray-400">Updated at 2026-04-28</p>

		<p class="mb-8 text-gray-300">
			MyIndo Cyber Media hereby grants you access to
			<a href="https://myindo.id/" class="text-blue-400 hover:underline">myindo.id</a> ("the Website")
			and invites you to purchase the services offered here.
		</p>

		<!-- Definitions -->
		<section class="mb-10">
			<h2 class="mb-4 text-2xl font-semibold">Definitions and key terms</h2>
			<p class="mb-4 text-gray-300">
				To help explain things as clearly as possible in this Disclaimer, every time any of these
				terms are referenced, are strictly defined as:
			</p>
			<ul class="space-y-3 text-gray-300">
				<li class="flex gap-2">
					<span class="mt-1 shrink-0 text-gray-500">—</span>
					<span>
						<strong class="text-white">Cookie:</strong> small amount of data generated by a website and
						saved by your web browser. It is used to identify your browser, provide analytics, remember
						information about you such as your language preference or login information.
					</span>
				</li>
				<li class="flex gap-2">
					<span class="mt-1 shrink-0 text-gray-500">—</span>
					<span>
						<strong class="text-white">Company:</strong> when this policy mentions "Company," "we," "us,"
						or "our," it refers to MyIndo Cyber Media, that is responsible for your information under
						this Disclaimer.
					</span>
				</li>
				<li class="flex gap-2">
					<span class="mt-1 shrink-0 text-gray-500">—</span>
					<span>
						<strong class="text-white">Service:</strong> refers to the service provided by MyIndo Cyber
						Media as described in the relative terms (if available) and on this platform.
					</span>
				</li>
				<li class="flex gap-2">
					<span class="mt-1 shrink-0 text-gray-500">—</span>
					<span>
						<strong class="text-white">Website:</strong> MyIndo Cyber Media's site, which can be accessed
						via this URL:
						<a href="https://myindo.id/" class="text-blue-400 hover:underline">https://myindo.id/</a>
					</span>
				</li>
				<li class="flex gap-2">
					<span class="mt-1 shrink-0 text-gray-500">—</span>
					<span>
						<strong class="text-white">You:</strong> a person or entity that is registered with MyIndo
						Cyber Media to use the Services.
					</span>
				</li>
			</ul>
		</section>

		<!-- Limited Liability -->
		<section class="mb-10">
			<h2 class="mb-4 text-2xl font-semibold">Limited liability</h2>
			<p class="mb-4 text-gray-300">
				MyIndo Cyber Media endeavours to update and/or supplement the content of the Website on a
				regular basis. Despite our care and attention, content may be incomplete and/or incorrect.
			</p>
			<p class="mb-4 text-gray-300">
				The materials offered on the Website are offered without any form of guarantee or claim to
				their correctness. These materials can be changed at any time without prior notice from
				MyIndo Cyber Media.
			</p>
			<p class="mb-4 text-gray-300">
				Particularly, all prices on the Website are stated subject to typing and programming errors.
				No liability is assumed for the implications of such errors. No agreement is concluded on the
				basis of such errors.
			</p>
			<p class="mb-4 text-gray-300">
				MyIndo Cyber Media shall not bear any liability for hyperlinks to websites or services of
				third parties included on the Website. From our Website, you can visit other websites by
				following hyperlinks to such external sites. While we strive to provide only quality links to
				useful and ethical websites, we have no control over the content and nature of these sites.
				These links to other websites do not imply a recommendation for all the content found on
				these sites. Site owners and content may change without notice and may occur before we have
				the opportunity to remove a link which may have gone 'bad'.
			</p>
			<p class="text-gray-300">
				Please be also aware that when you leave our Website, other sites may have different privacy
				policies and terms which are beyond our control. Please be sure to check the Privacy Policies
				of these sites as well as their "Terms of Service" before engaging in any business or
				uploading any information.
			</p>
		</section>

		<!-- Errors and Omissions -->
		<section class="mb-10">
			<h2 class="mb-4 text-2xl font-semibold">Errors and Omissions Disclaimer</h2>
			<p class="mb-4 text-gray-300">
				MyIndo Cyber Media is not responsible for any content, code or any other imprecision.
			</p>
			<p class="mb-4 text-gray-300">
				MyIndo Cyber Media does not provide warranties or guarantees.
			</p>
			<p class="text-gray-300">
				In no event shall MyIndo Cyber Media be liable for any special, direct, indirect,
				consequential, or incidental damages or any damages whatsoever, whether in an action of
				contract, negligence or other tort, arising out of or in connection with the use of the
				Service or the contents of the Service. MyIndo Cyber Media reserves the right to make
				additions, deletions, or modifications to the contents on the Service at any time without
				prior notice.
			</p>
		</section>

		<!-- General Disclaimer -->
		<section class="mb-10">
			<h2 class="mb-4 text-2xl font-semibold">General Disclaimer</h2>
			<p class="text-gray-300">
				The MyIndo Cyber Media Service and its contents are provided "as is" and "as available"
				without any warranty or representations of any kind, whether express or implied. MyIndo
				Cyber Media is a distributor and not a publisher of the content supplied by third parties; as
				such, MyIndo Cyber Media exercises no editorial control over such content and makes no
				warranty or representation as to the accuracy, reliability or currency of any information,
				content, service or merchandise provided through or accessible via the MyIndo Cyber Media
				Service. Without limiting the foregoing, MyIndo Cyber Media specifically disclaims all
				warranties and representations in any content transmitted on or in connection with the MyIndo
				Cyber Media Service or on sites that may appear as links on the MyIndo Cyber Media Service,
				or in the products provided as a part of, or otherwise in connection with, the MyIndo Cyber
				Media Service, including without limitation any warranties of merchantability, fitness for a
				particular purpose or non-infringement of third party rights. No oral advice or written
				information given by MyIndo Cyber Media or any of its affiliates, employees, officers,
				directors, agents, or the like will create a warranty. Price and availability information is
				subject to change without notice. Without limiting the foregoing, MyIndo Cyber Media does not
				warrant that the MyIndo Cyber Media Service will be uninterrupted, uncorrupted, timely, or
				error-free.
			</p>
		</section>

		<!-- Your Consent -->
		<section class="mb-10">
			<h2 class="mb-4 text-2xl font-semibold">Your Consent</h2>
			<p class="text-gray-300">
				We've updated our Disclaimer to provide you with complete transparency into what is being set
				when you visit our site and how it's being used. By using our Website, registering an
				account, or making a purchase, you hereby consent to our Disclaimer and agree to its terms.
			</p>
		</section>

		<!-- Changes -->
		<section class="mb-10">
			<h2 class="mb-4 text-2xl font-semibold">Changes To Our Disclaimer</h2>
			<p class="text-gray-300">
				Should we update, amend or make any changes to this document so that they accurately reflect
				our Service and policies. Unless otherwise required by law, those changes will be prominently
				posted here. Then, if you continue to use the Service, you will be bound by the updated
				Disclaimer. If you do not want to agree to this or any updated Disclaimer, you can delete
				your account.
			</p>
		</section>

		<!-- Contact -->
		<section class="mb-10">
			<h2 class="mb-4 text-2xl font-semibold">Contact Us</h2>
			<p class="mb-4 text-gray-300">
				Don't hesitate to contact us if you have any questions regarding this Disclaimer.
			</p>
			<ul class="space-y-2 text-gray-300">
				<li class="flex gap-2">
					<span class="shrink-0 text-gray-500">—</span>
					<span>
						Via Email:
						<a href="mailto:halo@myindo.id" class="text-blue-400 hover:underline">halo@myindo.id</a>
					</span>
				</li>
				<li class="flex gap-2">
					<span class="shrink-0 text-gray-500">—</span>
					<span>Via Phone number: +62 851-9551-8581</span>
				</li>
				<li class="flex gap-2">
					<span class="shrink-0 text-gray-500">—</span>
					<span>
						Via this Link:
						<a href="https://myindo.id/" class="text-blue-400 hover:underline">https://myindo.id/</a>
					</span>
				</li>
				<li class="flex gap-2">
					<span class="shrink-0 text-gray-500">—</span>
					<span>
						Via this Address: Eightyeight@Kasablanka Office Tower A Lantai 10 Unit E Jalan Casablanca
						Kav. 88 Kota Administrasi Jakarta Selatan, DKI Jakarta, 12870 Indonesia
					</span>
				</li>
			</ul>
		</section>
	</div>
</main>
